// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAjajmvz6HrOVy1HVuwik0K2ahVokWnuCg",
      authDomain: "tugasakhirmobileii.firebaseapp.com",
      projectId: "tugasakhirmobileii",
      storageBucket: "tugasakhirmobileii.appspot.com",
      messagingSenderId: "498155388349",
      appId: "1:498155388349:web:1df57316a5af78853566d4",
      measurementId: "G-W1VPC8P4M5");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAjajmvz6HrOVy1HVuwik0K2ahVokWnuCg",
      authDomain: "tugasakhirmobileii.firebaseapp.com",
      projectId: "tugasakhirmobileii",
      storageBucket: "tugasakhirmobileii.appspot.com",
      messagingSenderId: "498155388349",
      appId: "1:498155388349:web:1df57316a5af78853566d4",
      measurementId: "G-W1VPC8P4M5");

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyAjajmvz6HrOVy1HVuwik0K2ahVokWnuCg",
      authDomain: "tugasakhirmobileii.firebaseapp.com",
      projectId: "tugasakhirmobileii",
      storageBucket: "tugasakhirmobileii.appspot.com",
      messagingSenderId: "498155388349",
      appId: "1:498155388349:web:1df57316a5af78853566d4",
      measurementId: "G-W1VPC8P4M5");

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyAjajmvz6HrOVy1HVuwik0K2ahVokWnuCg",
      authDomain: "tugasakhirmobileii.firebaseapp.com",
      projectId: "tugasakhirmobileii",
      storageBucket: "tugasakhirmobileii.appspot.com",
      messagingSenderId: "498155388349",
      appId: "1:498155388349:web:1df57316a5af78853566d4",
      measurementId: "G-W1VPC8P4M5");

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyAjajmvz6HrOVy1HVuwik0K2ahVokWnuCg",
      authDomain: "tugasakhirmobileii.firebaseapp.com",
      projectId: "tugasakhirmobileii",
      storageBucket: "tugasakhirmobileii.appspot.com",
      messagingSenderId: "498155388349",
      appId: "1:498155388349:web:1df57316a5af78853566d4",
      measurementId: "G-W1VPC8P4M5");
}
